// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxwgbaasrqyjtvnbrxut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4d2diYWFzcnF5anR2bmJyeHV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NDk1NDIsImV4cCI6MjA2NTAyNTU0Mn0.IGJCoDbff_koX_bWWnY5oI_GlrhDbbhszLbD5GHxcZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);